// demo-vue/app/components/Home.vue
<template>
    <Page class="page">
        <ActionBar class="action-bar">
            <Label class="action-bar-title" text="Testing"></Label>
        </ActionBar>

        <GridLayout rows="auto, auto, *" class="form p-y-2">
            <!-- Add your page content here -->
            <GridLayout row="0" columns="*, auto" rows="*" class="p-8" backgroundColor="#f0f0f0">
                <TextField col="0" class="input input-rounded" :hint="hint"  v-model="text" backgroundColor="#fff"></TextField>
                <Button col="1" text="Add" @tap="addText" class="btn btn-primary"></Button>
            </GridLayout>

            <ListView for="item in items" class="list-group" row='2' @itemTap="remove">
                <v-template>
                    <StackLayout class="list-group-item">
                        <Label :text="item._id + '-' + item.name + ' -  ' + item.n + '  - ' + item.i" class="list-group-item-text"></Label>
                    </StackLayout>
                </v-template>
            </ListView>
        </GridLayout>
    </Page>
</template>

<script>

    import { DbBuilder } from 'nativescript-sqlite-access';
    import { databaseName, creationTableQueries, dropTableQueries, databaseTables } from "../db-setting";

    export default {
        data: function () {
            return {
                db: null,
                updateCounter: 0,
                items: [],cl
                hint: "Name something here",
                text: ""
            }
        },
        created: function () {
           this.db = DbBuilder(databaseName, {
                version: 1,
                createTableScriptsFn: () => {
                    return creationTableQueries;
                },
                dropTableScriptsFn: () => {
                    return dropTableQueries;
                }
            });
            this.reload();
        },
        methods: {
            addText: function () {
                let id = this.db.insert(databaseTables.PERSONS, {
                    name: this.text,
                    n: 45.23,
                    i: 1 * ++this.updateCounter
                });
                this.text = '';
                this.reload();
            },
            remove: function (event) {
                this.db.beginTransact();
                let test = this.items[event.index];
                let deleted = this.db.delete(databaseTables.PERSONS, '_id=?', [test._id]);
                console.log("deleted count.: ", deleted);
                this.db.commit();
                this.update();
                this.reload();
            },
            update: function () {
                const updated = this.db.update(databaseTables.PERSONS, {
                    name: "updateName-" + (this.updateCounter++)
                }, "_id=?", [1]);
                console.log("updated:", updated);
            },
            reload: function () {
                this.db.select(`SELECT * FROM ${databaseTables.PERSONS}`, null).process()
                .then(result => {
                    this.items = result;
                })
                .catch(err => {
                    console.log(err);
                    console.log("jajaja");
                });

                const reducerFn = (acc, next) => {
                    acc["name"] = acc["name"] || [];
                    acc["name"].push(next.name);
                    return acc;
                };

                const mapFn = (next) => {
                    return next.name;
                };

                this.db.query({ tableName: databaseTables.PERSONS })
                .reduce(reducerFn, {})
                .then(result => {
                    console.log("Reducing.: ");
                    console.log(result);
                })
                .catch(console.error);

                this.db.query({ tableName: databaseTables.PERSONS })
                .map(mapFn)
                .then(result => {
                    console.log("Mapping.: ");
                    console.log(result);
                })
                .catch(console.error);
            }
        }
    };
</script>

// demo-svelte/app/components/Home.svelte
<page>
    <actionBar title="Sqlite-access test" />
    <gridLayout rows="auto, *" class="form p-y-2">
        <!-- Add your page content here -->
       <gridLayout row="0" columns="*, auto" rows="auto" backgroundColor="#00389F19">
            <textField col="0" class="nt-input -rounded-sm p-x-4" hint="Name something here" bind:text="{ text }" isEnabled={!loading}></textField>
            <button col="1" text="Add" on:tap="{ addText }" class="-primary" isEnabled={!loading}></button>
       </gridLayout>

        <listView items="{ items }" class="list-group" row='1' on:itemTap="{ remove }">
            <Template let:item>
                <stackLayout class="list-group-item">
                    <label text="{ item._id + '-'+ item.name+ ' -  '+ item.n+ '  - '+ item.i }" class="list-group-item-text" />
                </stackLayout>
            </Template>
        </listView>
        <activityIndicator
            bind:busy="{loading}"
            row="0"
            rowSpan="2"
        />
    </gridLayout>
</page>

<script lang="ts">
    import { onMount, onDestroy } from 'svelte';
    import { Template } from "svelte-native/components"
    import { DbBuilder, IDatabase, DbCreationOptions } from 'nativescript-sqlite-access';
    import { version, databaseName, creationTableQueries, dropTableQueries, databaseTables } from "../db-setting";
    let text = '';
    let updateCounter = 0;
    let items: Array<Record<string, unknown>> = [];
    let localDb: IDatabase;
    let loading = true;
    
    function init() {
        localDb = DbBuilder(databaseName, <DbCreationOptions>{
            version,
            createTableScriptsFn: () => creationTableQueries,
            dropTableScriptsFn: () => dropTableQueries
        });

        if(loading) {
            reload();
        }
    }

    function addText() {
        let id = localDb.insert(databaseTables.PERSONS, {
            name: text,
            n: 45.5,
            i: 1 * ++updateCounter
        });
        console.log("id", id);
        text = ''
        reload();
    }

    function remove(event: {index: number}) {
        localDb.beginTransact();
        let test = items[event.index];
        let deleted = localDb.delete(databaseTables.PERSONS, '_id=?', [test._id]);
        console.log("deleted count.: ", deleted);
        localDb.commit();
        update();
        reload();
    }

    function update() {
        const updated = localDb.update(databaseTables.PERSONS, {
            name: "updateName-" + (updateCounter++)
        }, "_id=?", [1]);
        console.log("updated:", updated);
    }

    function reload() {
        if (!localDb) return;
        
        const reducerFn = (acc: Record<string, string[]>, next: Record<string, unknown>) => {
            acc["name"] = acc["name"] || [];
            acc["name"].push(next.name as string);
            return acc;
        };

        const mapFn = (next: Record<string, unknown>) => {
            return next.name;
        };

        console.log("------------- as select and reduce -------------");
        localDb.select(`SELECT * FROM ${databaseTables.PERSONS}`)
        .process(reducerFn, {})
        .then(result => {
            console.log("Reducing.: ");
            console.log(result);
        })
        .catch(console.error);

        console.log("------------- as query and map -------------");
        localDb.query({tableName: databaseTables.PERSONS})
        .process(mapFn)
        .then(result => {
            console.log("Mapping.: ");
            console.log(result);
        })
        .catch(console.error);


        console.log("------------- as generator -------------");
        localDb.query({tableName: databaseTables.PERSONS }).asGenerator()
		.then((asGenerator) => {
			items = [];
			const id = setInterval(() => {
				const it = asGenerator.next();
				if(it.done) {
					clearInterval(id);
					loading = false;
					return;
				}
				items = [].concat(items, [it.value]);
			}, 1000);
		});
    }
    
    onMount(init);
    onDestroy(() => {
        localDb.close();    
        localDb = null;
    });
</script>
